document.write("<div id='end'>")
    document.write("<div>");
        document.write("<div class='topic-header'>CONTACT US</div>");
    document.write("</div>");
    document.write("<div>");
        document.write("<div class='sub-header'>BAND MANAGER</div>");
        document.write("<div class='contact'>");
            document.write("<div class='label'>NAME:</div>");
            document.write("<div class='info'>MITCHELL FINITZ</div>");
        document.write("</div>");
        document.write("<div class='contact'>");
            document.write("<div class='label'>PHONE:</div>");
            document.write("<div class='info'>617-RECURSE</div>");
        document.write("</div>");
        document.write("<div class='contact'>");
            document.write("<div class='label'>EMAIL:</div>");
            document.write("<div class='info'>MFINIT02@TUFTS.EDU</div>");
        document.write("</div>");
    document.write("</div>");
    document.write("<div>");
        document.write("<div class='sub-header'>SOCIAL MEDIA</div>");
        document.write("<div class='social'>@rhythim-recursion-ne</div>");
        document.write("<div class='icons'>");
            document.write("<a href='https://accounts.spotify.com/en/login' target='_blank'>");
                document.write("<i class='fa-brands fa-spotify'></i>");
            document.write("</a>");
            document.write("<a href='https://www.youtube.com/' target='_blank'>");
                document.write("<i class='fa-brands fa-youtube'></i>");
            document.write("</a>");
            document.write("<a href='https://www.instagram.com/' target='_blank'>");
                document.write("<i class='fa-brands fa-square-instagram'></i>");
            document.write("</a>");
            document.write("<a href='https://www.facebook.com/' target='_blank'>");
                document.write("<i class='fa-brands fa-facebook'></i>");
            document.write("</a>");
            document.write("<a href='https://x.com/' target='_blank'>");
                document.write("<i class='fa-brands fa-square-x-twitter'></i>");
            document.write("</a>");
        document.write("</div>");
    document.write("</div>");
document.write("</div>")