document.write("<div id='nav'>");
    document.write("<ul>");
        document.write("<li><a href='home.html'>HOME</a></li>");
        document.write("<li><a href='book.html'>BOOK</a></li>");
        document.write("<li><a href='songs.html'>SONGS</a></li>");
        document.write("<li><a href='home.html'><img src='../images/logo.png' alt='Band logo'></a></li>");
        document.write("<li><a href='merchandise.html'>MERCHANDISE</a></li>");
        document.write("<li><a href='faq.html'>FAQ</a></li>");
    document.write("</ul>");
document.write("</div>");
document.write("<div id='mobile-menu-banner'>");
    document.write("<div id='drop-down-block'>");
        document.write("<label for='mobile-checkbox'>");
            document.write("<div>");
                document.write("<span></span>");
                document.write("<span></span>");
                document.write("<span style='margin-bottom:0px;'></span>");
            document.write("</div>");
        document.write("</label>");
        document.write("<input id='mobile-checkbox' type='checkbox' name='mobile-checkbox' />");
        document.write("<div id='mobile-nav-bar'>");
            document.write("<ul>");
                document.write("<li><a href='home.html'>HOME</a></li>");
                document.write("<li><a href='book.html'>BOOK</a></li>");
                document.write("<li><a href='songs.html'>SONGS</a></li>");
                document.write("<li><a href='merchandise.html'>MERCHANDISE</a></li>");
                document.write("<li><a href='faq.html'>FAQ</a></li>");
            document.write("</ul>");
        document.write("</div>");
    document.write("</div>");
document.write("</div>");